; bottom-left vram area $00 - $7F
	tilepal 0, GRAY, GRAY, GRAY, YELLOW, GREEN, GRAY, RED, RED
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, RED, WATER
	tilepal 0, RED, RED, GREEN, GREEN, WATER, GREEN, GREEN, RED
	tilepal 0, RED, WATER, RED, RED, WATER, WATER, WATER, RED
	tilepal 0, WATER, WATER, RED, RED, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, GRAY, GRAY, RED
	tilepal 0, RED, RED, RED, GRAY, RED, RED, RED, RED
	tilepal 0, RED, RED, WATER, YELLOW, YELLOW, RED, RED, BROWN
	tilepal 0, RED, RED, RED, RED, GRAY, GRAY, GRAY, ROOF
	tilepal 0, RED, RED, WATER, RED, WATER, RED, WATER, RED
	tilepal 0, WATER, WATER, RED, ROOF, ROOF, TEXT, TEXT, TEXT
rept 16
    db $ff
endr

; bottom-right vram area $80 - $FF
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT